package org.nvgu.util;

public enum LinearGradientDirection {
    LEFT_TO_RIGHT,
    RIGHT_TO_LEFT,
    TOP_TO_BOTTOM,
    BOTTOM_TO_TOP,
    DIAGONAL_LEFT_TO_RIGHT_UP,
    DIAGONAL_LEFT_TO_RIGHT_DOWN,
    DIAGONAL_RIGHT_TO_LEFT_UP,
    DIAGONAL_RIGHT_TO_LEFT_DOWN
}
